SET NAMES utf8mb4;

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行', '存款优选系列', '示例活期增强存款', 'DEMO-DEP-CALL', '存款', '保守', '随时可用', '随时可用', 1.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '高于活期', '示例费率：无销售服务费', '支持按规则支取，具体以产品条款为准', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合保守型客户作日常备用金管理参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('新手','工资结余客户','退休客户'), JSON_ARRAY('存款','低风险','开放式'), '存款产品仍需核验实际利率、期限、提前支取规则和销售权限。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-DEP-CALL');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行', '存款优选系列', '示例三月安心存款', 'DEMO-DEP-090', '存款', '保守', '3个月', '可封闭持有', 5000.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '稳健收益', '示例费率：无销售服务费', '持有到期按规则支取，提前支取规则以条款为准', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合保守型客户三个月资金安排参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('新手','退休客户','工资结余客户'), JSON_ARRAY('存款','低风险','封闭'), '推荐前需确认客户资金三个月内无刚性支取需求。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-DEP-090');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '保守固收系列', '示例保守半年固收', 'DEMO-FI-CONS-180', '固定收益类', '保守', '6个月', '可封闭持有', 10000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '封闭180天，到期后按规则兑付', DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_ADD(NOW(), INTERVAL 210 DAY), '适合保守型及以上、可接受半年封闭安排的客户', JSON_OBJECT('bond','90%','cash','10%'), JSON_ARRAY('退休客户','工资结余客户'), JSON_ARRAY('封闭','低波动','债券'), '固定收益类产品不等于保本，需充分揭示净值波动和流动性限制。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-FI-CONS-180');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '月度开放系列', '示例稳健月月开放固收', 'DEMO-FI-MONTHLY', '固定收益类', '稳健', '1个月', '随时可用', 1000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '每月开放一次赎回，到账规则以说明书为准', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合稳健型及以上客户短期限资金安排参考', JSON_OBJECT('bond','84%','cash','16%'), JSON_ARRAY('新手','工资结余客户'), JSON_ARRAY('开放式','债券','短期限'), '月度开放不等于实时到账，需提示开放日和到账周期。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-FI-MONTHLY');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '平衡开放系列', '示例平衡半年开放混合', 'DEMO-MIX-180-FLEX', '混合类', '平衡', '6个月', '短期可能用钱', 10000.00, 'CNY', '权益和固收资产占比会影响净值波动', '接受波动换收益', '示例费率：按产品说明书执行', '定期开放赎回，具体以产品说明书为准', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_ADD(NOW(), INTERVAL 210 DAY), '适合平衡型及以上、可接受中等波动的客户', JSON_OBJECT('bond','65%','equity','20%','cash','15%'), JSON_ARRAY('企业主','工资结余客户'), JSON_ARRAY('开放式','波动收益','权益'), '不得向风险承受能力低于平衡型的客户推荐。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-MIX-180-FLEX');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行代销', '基金优选系列', '示例进取六个月基金观察', 'DEMO-FUND-ADV-180', '基金', '进取', '6个月', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：申购赎回费以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合进取型、能承受较大净值波动的客户', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主','工资结余客户'), JSON_ARRAY('基金','开放式','波动收益'), '基金产品不保证本金和收益，需完成代销适当性匹配。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-FUND-ADV-180');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行代销', '基金优选系列', '示例进取一年基金配置', 'DEMO-FUND-ADV-365', '基金', '进取', '1年以上', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：申购赎回费以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合进取型、有一年以上配置计划的客户', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主'), JSON_ARRAY('基金','开放式','权益','波动收益'), '不得推荐给风险承受能力不足客户。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-FUND-ADV-365');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PERSONAL', 1, '客户经理', NULL, 1, '北京分行', '客户经理精选', '示例张晨安心三月存款', 'DEMO-MGR-DEP-090', '存款', '保守', '3个月', '可封闭持有', 5000.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '稳健收益', '示例费率：无销售服务费', '持有到期按规则支取', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 180 DAY), '适合保守型客户三个月资金安排参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('新手','退休客户','工资结余客户'), JSON_ARRAY('客户经理精选','存款','低风险'), '需核验实际存款规则、提前支取规则和客户适当性。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-MGR-DEP-090');

INSERT INTO `investment_product` (`source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`, `issuer_name`, `product_series`, `product_name`, `product_code`, `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`, `min_amount`, `currency`, `expected_return_desc`, `return_type`, `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`, `suitability_profile`, `asset_allocation`, `target_customer`, `tags`, `compliance_note`, `status`, `created_at`, `updated_at`)
SELECT 'PERSONAL', 1, '客户经理', NULL, 1, '北京分行', '客户经理精选', '示例张晨进取基金观察', 'DEMO-MGR-FUND-ADV', '基金', '进取', '1年以上', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合进取型、有中长期配置计划的客户', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主'), JSON_ARRAY('客户经理精选','基金','波动收益'), '仅适合进取型客户，不得弱化净值波动和本金损失风险。', 'AVAILABLE', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `investment_product` WHERE `product_code` = 'DEMO-MGR-FUND-ADV');
