SET NAMES utf8mb4;

INSERT INTO `investment_product` (
  `source_type`, `owner_user_id`, `scope_type`, `scope_branch_id`, `scope_manager_id`,
  `issuer_name`, `product_series`, `product_name`, `product_code`,
  `product_type`, `risk_level`, `investment_horizon`, `liquidity_type`,
  `min_amount`, `currency`, `expected_return_desc`, `return_type`,
  `fee_desc`, `redemption_rule`, `sale_start_at`, `sale_end_at`,
  `suitability_profile`, `asset_allocation`, `target_customer`, `tags`,
  `compliance_note`, `status`, `created_at`, `updated_at`
)
SELECT
  p.`source_type`, p.`owner_user_id`, p.`scope_type`, p.`scope_branch_id`, p.`scope_manager_id`,
  p.`issuer_name`, p.`product_series`, p.`product_name`, p.`product_code`,
  p.`product_type`, p.`risk_level`, p.`investment_horizon`, p.`liquidity_type`,
  p.`min_amount`, p.`currency`, p.`expected_return_desc`, p.`return_type`,
  p.`fee_desc`, p.`redemption_rule`, p.`sale_start_at`, p.`sale_end_at`,
  p.`suitability_profile`, p.`asset_allocation`, p.`target_customer`, p.`tags`,
  p.`compliance_note`, p.`status`, p.`created_at`, p.`updated_at`
FROM (
  SELECT 'PUBLIC' AS `source_type`, NULL AS `owner_user_id`, '全行' AS `scope_type`, NULL AS `scope_branch_id`, NULL AS `scope_manager_id`, '本行理财子公司' AS `issuer_name`, '现金管理系列' AS `product_series`, '示例零钱快取现金管理B' AS `product_name`, 'DEMO-CASH-FAST-B' AS `product_code`, '现金管理' AS `product_type`, '保守' AS `risk_level`, '随时可用' AS `investment_horizon`, '随时可用' AS `liquidity_type`, 1.00 AS `min_amount`, 'CNY' AS `currency`, '业绩比较基准随市场调整，非收益承诺' AS `expected_return_desc`, '高于活期' AS `return_type`, '示例费率：销售服务费按说明书执行' AS `fee_desc`, '工作日开放申赎，到账以说明书为准' AS `redemption_rule`, DATE_SUB(NOW(), INTERVAL 20 DAY) AS `sale_start_at`, DATE_ADD(NOW(), INTERVAL 365 DAY) AS `sale_end_at`, '适合保守型客户短期流动性管理参考' AS `suitability_profile`, JSON_OBJECT('cash','75%','bond','25%') AS `asset_allocation`, JSON_ARRAY('新手','工资结余客户','退休客户') AS `target_customer`, JSON_ARRAY('开放式','现金管理','低风险') AS `tags`, '现金管理类产品不承诺收益，需提示净值波动和赎回到账规则。' AS `compliance_note`, 'AVAILABLE' AS `status`, NOW() AS `created_at`, NOW() AS `updated_at`
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行', '存款优选系列', '示例六个月安心存款', 'DEMO-DEP-180', '存款', '保守', '6个月', '可封闭持有', 10000.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '稳健收益', '示例费率：无销售服务费', '持有到期按规则支取，提前支取规则以条款为准', DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合保守型客户半年资金安排参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('新手','退休客户','工资结余客户'), JSON_ARRAY('存款','低风险','封闭'), '需核验实际存款规则、提前支取规则和客户资金安排。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '短债稳健系列', '示例短债稳健60天', 'DEMO-BOND-060', '固定收益类', '稳健', '1个月', '短期可能用钱', 5000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '最短持有期后按开放日规则赎回', DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合稳健型及以上客户短期限资金安排参考', JSON_OBJECT('bond','86%','cash','14%'), JSON_ARRAY('新手','工资结余客户'), JSON_ARRAY('短期限','债券','低波动'), '短债产品仍存在净值波动，推荐前需完成适当性匹配。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '固收开放系列', '示例稳健季季开放固收', 'DEMO-FI-QTR-FLEX', '固定收益类', '稳健', '3个月', '随时可用', 10000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '季度开放申赎，具体开放日以说明书为准', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合稳健型客户季度资金安排参考', JSON_OBJECT('bond','82%','cash','18%'), JSON_ARRAY('工资结余客户','退休客户'), JSON_ARRAY('开放式','债券','季度开放'), '开放式不等于随时到账，需说明开放日和到账周期。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '固收增强系列', '示例一年开放固收增强', 'DEMO-FI-365-FLEX', '固定收益类', '稳健', '1年以上', '短期可能用钱', 50000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '定期开放赎回，到账规则以说明书为准', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_ADD(NOW(), INTERVAL 300 DAY), '适合稳健型及以上、中长期配置但需保留开放安排的客户', JSON_OBJECT('bond','78%','cash','12%','preferred','10%'), JSON_ARRAY('企业主','退休客户'), JSON_ARRAY('开放式','债券','中长期'), '需说明定期开放规则和净值波动风险。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '平衡配置系列', '示例平衡三个月观察', 'DEMO-MIX-090', '混合类', '平衡', '3个月', '短期可能用钱', 10000.00, 'CNY', '权益和固收资产占比影响净值波动', '接受波动换收益', '示例费率：按产品说明书执行', '定期开放，赎回到账以说明书为准', DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_ADD(NOW(), INTERVAL 220 DAY), '适合平衡型及以上、能接受一定波动的客户', JSON_OBJECT('bond','70%','equity','15%','cash','15%'), JSON_ARRAY('工资结余客户','企业主'), JSON_ARRAY('开放式','波动收益','混合'), '不得向保守或稳健客户推荐超出风险承受能力的产品。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行理财子公司', '平衡配置系列', '示例平衡六个月封闭配置', 'DEMO-MIX-180-CLOSE', '混合类', '平衡', '6个月', '可封闭持有', 20000.00, 'CNY', '净值随债券和权益市场波动', '接受波动换收益', '示例费率：按产品说明书执行', '封闭180天，到期按规则兑付', DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_ADD(NOW(), INTERVAL 220 DAY), '适合平衡型及以上、可接受半年封闭的客户', JSON_OBJECT('bond','62%','equity','25%','cash','13%'), JSON_ARRAY('企业主','工资结余客户'), JSON_ARRAY('封闭','波动收益','混合'), '需确认客户风险等级不低于平衡型，并充分提示封闭期。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行代销', '基金优选系列', '示例平衡债基一年配置', 'DEMO-FUND-BAL-365', '基金', '平衡', '1年以上', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：申购赎回费以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 35 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合平衡型及以上且了解基金波动的客户', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主','工资结余客户'), JSON_ARRAY('基金','开放式','波动收益'), '基金不保证本金和收益，需完成代销适当性匹配。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行代销', '基金优选系列', '示例进取权益六个月观察', 'DEMO-EQ-180-FLEX', '基金', '进取', '6个月', '短期可能用钱', 100.00, 'CNY', '权益市场波动较大，不代表实际收益', '接受波动换收益', '示例费率：按基金合同执行', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 28 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '仅适合进取型且能承受较大净值波动的客户', JSON_OBJECT('equity','80%','cash','20%'), JSON_ARRAY('企业主'), JSON_ARRAY('基金','权益','开放式','波动收益'), '不得推荐给风险承受能力不足客户。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '全行', NULL, NULL, '本行代销', '保障配置系列', '示例养老保障配置计划', 'DEMO-INS-PENSION', '保险', '稳健', '1年以上', '可封闭持有', 20000.00, 'CNY', '保险利益以合同条款为准', '稳健收益', '示例费率：费用结构以保险合同为准', '退保可能产生损失，现金价值以合同为准', DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合有长期保障和资产规划需求的稳健型及以上客户', JSON_OBJECT('insurance','100%'), JSON_ARRAY('退休客户','企业主'), JSON_ARRAY('保险','长期','封闭'), '保险不是银行存款，需按保险销售规则完成风险提示和双录要求。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 2, NULL, '北京分行', '北京分行现金系列', '示例北京分行日日盈', 'DEMO-BJ-CASH-DAY', '现金管理', '保守', '随时可用', '随时可用', 1.00, 'CNY', '业绩比较基准随市场调整，非收益承诺', '高于活期', '示例费率：按说明书执行', '工作日开放申赎', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_ADD(NOW(), INTERVAL 180 DAY), '适合北京分行保守型客户流动性管理参考', JSON_OBJECT('cash','78%','bond','22%'), JSON_ARRAY('新手','工资结余客户','退休客户'), JSON_ARRAY('分行特色','现金管理','开放式'), '分行范围产品需确认客户所属机构和销售权限。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 2, NULL, '北京分行', '北京分行存款系列', '示例北京分行半年安心存款', 'DEMO-BJ-DEP-180', '存款', '保守', '6个月', '可封闭持有', 10000.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '稳健收益', '示例费率：无销售服务费', '持有到期按规则支取', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合北京分行保守型客户半年资金安排参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('退休客户','工资结余客户'), JSON_ARRAY('分行特色','存款','低风险'), '需核验实际存款规则和提前支取规则。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 2, NULL, '北京分行', '北京分行固收系列', '示例北京分行月月稳', 'DEMO-BJ-FI-030', '固定收益类', '稳健', '1个月', '短期可能用钱', 5000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '月度开放，开放期可赎回', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_ADD(NOW(), INTERVAL 180 DAY), '适合北京分行稳健型客户短期限资金安排参考', JSON_OBJECT('bond','85%','cash','15%'), JSON_ARRAY('新手','工资结余客户'), JSON_ARRAY('分行特色','债券','短期限'), '月度开放不等于实时到账，需提示开放日。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 2, NULL, '北京分行', '北京分行配置系列', '示例北京分行平衡一年配置', 'DEMO-BJ-MIX-365', '混合类', '平衡', '1年以上', '可封闭持有', 50000.00, 'CNY', '净值可能随权益和债券市场波动', '接受波动换收益', '示例费率：按产品说明书执行', '一年持有期，到期后可按开放日赎回', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_ADD(NOW(), INTERVAL 260 DAY), '适合北京分行平衡型及以上客户中长期配置参考', JSON_OBJECT('bond','60%','equity','25%','cash','15%'), JSON_ARRAY('企业主'), JSON_ARRAY('分行特色','封闭','波动收益'), '不得向风险承受能力低于平衡型客户推荐。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 2, NULL, '北京分行', '北京分行基金系列', '示例北京分行进取基金优选', 'DEMO-BJ-FUND-ADV', '基金', '进取', '1年以上', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合北京分行进取型客户中长期配置参考', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主'), JSON_ARRAY('分行特色','基金','权益','开放式'), '仅适合进取型客户，不得弱化波动和本金损失风险。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 3, NULL, '上海分行', '上海分行现金系列', '示例上海分行现金添利', 'DEMO-SH-CASH-PLUS', '现金管理', '保守', '随时可用', '随时可用', 1.00, 'CNY', '业绩比较基准随市场调整，非收益承诺', '高于活期', '示例费率：按说明书执行', '工作日开放申赎', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_ADD(NOW(), INTERVAL 180 DAY), '适合上海分行保守型客户流动性管理参考', JSON_OBJECT('cash','76%','bond','24%'), JSON_ARRAY('新手','工资结余客户','退休客户'), JSON_ARRAY('分行特色','现金管理','开放式'), '分行范围产品需确认客户所属机构和销售权限。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 3, NULL, '上海分行', '上海分行存款系列', '示例上海分行三月安心存款', 'DEMO-SH-DEP-090', '存款', '保守', '3个月', '可封闭持有', 5000.00, 'CNY', '示例存款利率描述，以实际挂牌和产品规则为准', '稳健收益', '示例费率：无销售服务费', '持有到期按规则支取', DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_ADD(NOW(), INTERVAL 240 DAY), '适合上海分行保守型客户三个月资金安排参考', JSON_OBJECT('deposit','100%'), JSON_ARRAY('新手','退休客户','工资结余客户'), JSON_ARRAY('分行特色','存款','低风险'), '需核验实际存款规则和提前支取规则。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 3, NULL, '上海分行', '上海分行固收系列', '示例上海分行一年稳享固收', 'DEMO-SH-FI-365', '固定收益类', '稳健', '1年以上', '可封闭持有', 50000.00, 'CNY', '业绩比较基准为区间表达，非收益承诺', '稳健收益', '示例费率：按产品说明书执行', '封闭运作，到期按规则兑付', DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_ADD(NOW(), INTERVAL 300 DAY), '适合上海分行稳健型客户中长期配置参考', JSON_OBJECT('bond','83%','cash','17%'), JSON_ARRAY('退休客户','企业主'), JSON_ARRAY('分行特色','债券','封闭'), '需提示封闭期、净值波动和销售权限要求。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 3, NULL, '上海分行', '上海分行配置系列', '示例上海分行平衡半年开放', 'DEMO-SH-MIX-180', '混合类', '平衡', '6个月', '短期可能用钱', 20000.00, 'CNY', '净值可能随权益和债券市场波动', '接受波动换收益', '示例费率：按产品说明书执行', '定期开放赎回，到账规则以说明书为准', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_ADD(NOW(), INTERVAL 260 DAY), '适合上海分行平衡型及以上客户半年资金配置参考', JSON_OBJECT('bond','63%','equity','22%','cash','15%'), JSON_ARRAY('企业主','工资结余客户'), JSON_ARRAY('分行特色','开放式','波动收益'), '不得向风险承受能力低于平衡型客户推荐。', 'AVAILABLE', NOW(), NOW()
  UNION ALL SELECT 'PUBLIC', NULL, '分行', 3, NULL, '上海分行', '上海分行基金系列', '示例上海分行进取权益优选', 'DEMO-SH-FUND-ADV', '基金', '进取', '1年以上', '短期可能用钱', 100.00, 'CNY', '基金净值随市场波动，无固定收益', '接受波动换收益', '示例费率：以基金合同为准', '开放式基金，赎回到账以基金规则为准', DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_ADD(NOW(), INTERVAL 365 DAY), '适合上海分行进取型客户中长期配置参考', JSON_OBJECT('fund','100%'), JSON_ARRAY('企业主'), JSON_ARRAY('分行特色','基金','权益','开放式'), '仅适合进取型客户，不得弱化波动和本金损失风险。', 'AVAILABLE', NOW(), NOW()
) AS p
WHERE NOT EXISTS (
  SELECT 1
  FROM `investment_product` existing
  WHERE existing.`product_code` = p.`product_code`
);
